GET http://localhost:3000/hotel

###

GET http://localhost:3000/hotel/Test2

###

POST http://localhost:3000/hotel
Content-Type: application/json

{
    "name": "Nächstes Hotel",
    "short_name": "Strinhjkhkh"
}

###

PUT http://localhost:3000/hotel/Test2
Content-Type: application/json

{
    "short_name": "NEU"
}
###

DELETE http://localhost:3000/hotel/681faa810d493b1ee6daba26

###
